version: '3.8'

services:
  web:
    image: armboy/wsra:latest 
    restart: always
    environment:
      DATABASE_URL: "postgresql://sakdithat:1q2W3e4R@10.0.0.102:5432/wsra?schema=public"
      NEXTAUTH_SECRET: "armboy"
      NEXTAUTH_URL: "http://10.0.0.101:3000"
    ports:
      - "3000:3000"